### ISSUE TITLE
centos 8.5 部署v1.2.1  提示错误

### ISSUE THREAD

**Issue by xy2019devl** [kubeclipper/kubeclipper#270]
Last login: Fri Oct 14 15:15:03 2022 from 192.168.3.226
[root@localhost ~]# systemctl stop firewalld.service 
[root@localhost ~]# systemctl disable firewalld.service 
Removed /etc/systemd/system/multi-user.target.wants/firewalld.service.
Removed /etc/systemd/system/dbus-org.fedoraproject.FirewallD1.service.
[root@localhost ~]# getenforce 
Disabled
[root@localhost ~]# curl -sfL https://oss.kubeclipper.io/kcctl.sh | KC_REGION=cn bash -
[INFO]  The v1.2.1 version will be installed
[INFO]  KC_REGION is assigned cn, kc.env file will be created
[INFO]  env: Creating environment file /etc/kc/kc.env}
mkdir: created directory '/etc/kc'
[INFO]  Downloading package https://oss.kubeclipper.io/kc/v1.2.1/kc-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 47.7M  100 47.7M    0     0  2994k      0  0:00:16  0:00:16 --:--:-- 3490k
kubeclipper-server
kubeclipper-agent
kcctl
[INFO]  Installing kcctl to /usr/local/bin/kcctl

  Kcctl has been installed successfully!
    Run 'kcctl version' to view the version.
    Run 'kcctl -h' for more help.

        __ ______________________
       / //_/ ____/ ____/_  __/ /
      / ,< / /   / /     / / / /
     / /| / /___/ /___  / / / /___
    /_/ |_\____/\____/ /_/ /_____/
    repository: github.com/kubeclipper
  
[root@localhost ~]# kcctl deploy --user root --passwd 1qaz2wsx
2022-10-18T12:25:08+08:00	INFO	Using auto detected IPv4 address on interface ens192: 192.168.3.79/24
[2022-10-18T12:25:08+08:00][INFO] run in aio mode.
[2022-10-18T12:25:09+08:00][INFO] ============>kc-etcd PRECHECK ...
[2022-10-18T12:25:10+08:00][INFO] ============>kc-etcd PRECHECK OK!
[2022-10-18T12:25:10+08:00][INFO] ============>kc-server PRECHECK ...
[2022-10-18T12:25:10+08:00][INFO] ============>kc-server PRECHECK OK!
[2022-10-18T12:25:10+08:00][INFO] ============>kc-agent PRECHECK ...
[2022-10-18T12:25:10+08:00][INFO] ============>kc-agent PRECHECK OK!
[2022-10-18T12:25:10+08:00][INFO] ============>TIME-LAG PRECHECK ...
[2022-10-18T12:25:10+08:00][INFO] BaseLine Time: 2022-10-18T12:25:10+08:00
[2022-10-18T12:25:10+08:00][INFO] [192.168.3.79] -0.544791697 seconds
[2022-10-18T12:25:10+08:00][INFO] all nodes time lag less then 5 seconds
[2022-10-18T12:25:10+08:00][INFO] ============>TIME-LAG PRECHECK OK!
[2022-10-18T12:25:10+08:00][INFO] ============>NTP PRECHECK ...
[2022-10-18T12:25:10+08:00][WARNING] chronyd or ntpd service not running, may cause service internal error
[2022-10-18T12:25:10+08:00][ERROR] ===========>NTP PRECHECK FAILED!
Ignore this error, still install? Please input (yes/no)yes
[2022-10-18T12:25:13+08:00][INFO] ============>sudo PRECHECK ...
[2022-10-18T12:25:13+08:00][INFO] ============>sudo PRECHECK OK!
[2022-10-18T12:25:13+08:00][INFO] ============>ipDetect PRECHECK ...
[2022-10-18T12:25:14+08:00][INFO] ============>ipDetect PRECHECK OK!
[2022-10-18T12:25:15+08:00][INFO] [192.168.3.79]transfer total size is: 1.64KB ;speed is 1KB
[2022-10-18T12:25:16+08:00][INFO] [192.168.3.79]transfer total size is: 1.09KB ;speed is 1KB
[2022-10-18T12:25:16+08:00][INFO] [192.168.3.79]transfer total size is: 1.64KB ;speed is 1KB
[2022-10-18T12:25:17+08:00][INFO] [192.168.3.79]transfer total size is: 1.20KB ;speed is 1KB
[2022-10-18T12:25:18+08:00][INFO] [192.168.3.79]transfer total size is: 1.64KB ;speed is 1KB
[2022-10-18T12:25:18+08:00][INFO] [192.168.3.79]transfer total size is: 1.20KB ;speed is 1KB
[2022-10-18T12:25:19+08:00][INFO] [192.168.3.79]transfer total size is: 1.64KB ;speed is 1KB
[2022-10-18T12:25:19+08:00][INFO] [192.168.3.79]transfer total size is: 1.20KB ;speed is 1KB
[2022-10-18T12:25:20+08:00][INFO] [192.168.3.79]transfer total size is: 1.64KB ;speed is 1KB
[2022-10-18T12:25:21+08:00][INFO] [192.168.3.79]transfer total size is: 1.21KB ;speed is 1KB
[2022-10-18T12:25:21+08:00][INFO] [192.168.3.79]transfer total size is: 1.64KB ;speed is 1KB
[2022-10-18T12:25:22+08:00][INFO] [192.168.3.79]transfer total size is: 1.23KB ;speed is 1KB
[2022-10-18T12:25:22+08:00][INFO] [192.168.3.79]transfer total size is: 1.64KB ;speed is 1KB
[2022-10-18T12:25:23+08:00][INFO] [192.168.3.79]transfer total size is: 1.23KB ;speed is 1KB
[2022-10-18T12:25:23+08:00][INFO] [192.168.3.79]transfer total size is: 1.64KB ;speed is 1KB
[2022-10-18T12:25:24+08:00][INFO] [192.168.3.79]transfer total size is: 1.09KB ;speed is 1KB
[2022-10-18T12:25:25+08:00][INFO] [192.168.3.79]transfer total size is: 1.64KB ;speed is 1KB
[2022-10-18T12:25:25+08:00][INFO] [192.168.3.79]transfer total size is: 1.23KB ;speed is 1KB
[2022-10-18T12:25:26+08:00][INFO] [192.168.3.79]transfer total size is: 1.64KB ;speed is 1KB
[2022-10-18T12:25:26+08:00][INFO] [192.168.3.79]transfer total size is: 1.23KB ;speed is 1KB
[2022-10-18T12:25:27+08:00][INFO] ------ Send packages ------
--2022-10-18 12:25:27--  https://oss.kubeclipper.io/release/v1.2.1/kc-amd64.tar.gz
Resolving oss.kubeclipper.io (oss.kubeclipper.io)... 161.117.155.63
Connecting to oss.kubeclipper.io (oss.kubeclipper.io)|161.117.155.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 810999962 (773M) [application/gzip]
Saving to: ‘kc-amd64.tar.gz’

kc-amd64.tar.gz                                      100%[====================================================================================================================>] 773.43M  4.05MB/s    in 2m 56s  

2022-10-18 12:28:23 (4.40 MB/s) - ‘kc-amd64.tar.gz’ saved [810999962/810999962]

192.168.3.79: done!   
[2022-10-18T12:28:53+08:00][INFO] ------ Install kc-etcd ------
[2022-10-18T12:29:01+08:00][INFO] ------ Install kc-server ------
[2022-10-18T12:29:57+08:00][INFO] ------ Install kc-agent ------
[2022-10-18T12:30:04+08:00][INFO] ------ Install kc-console ------
[2022-10-18T12:30:09+08:00][INFO] ------ Delete intermediate files ------
[2022-10-18T12:30:13+08:00][INFO] ------ Upload configs ------
[2022-10-18T12:30:13+08:00][FATAL] error during connect: Post "http://192.168.3.79:8080/oauth/login": dial tcp 192.168.3.79:8080: connect: connection refused
goroutine 1 [running]:
github.com/kubeclipper/kubeclipper/pkg/cli/logger.stacks(0x0)
	/home/runner/work/kubeclipper/kubeclipper/pkg/cli/logger/logger.go:163 +0x89
github.com/kubeclipper/kubeclipper/pkg/cli/logger.(*loggingT).output(0x1f47160?, 0xc00085e4b0?, 0x3)
	/home/runner/work/kubeclipper/kubeclipper/pkg/cli/logger/logger.go:130 +0x75
github.com/kubeclipper/kubeclipper/pkg/cli/logger.(*loggingT).println(0xc000b43888?, 0x1f64420?, {0xc000b438a0, 0x1, 0x1})
	/home/runner/work/kubeclipper/kubeclipper/pkg/cli/logger/logger.go:150 +0x85
github.com/kubeclipper/kubeclipper/pkg/cli/logger.Fatal(...)
	/home/runner/work/kubeclipper/kubeclipper/pkg/cli/logger/logger.go:320
github.com/kubeclipper/kubeclipper/pkg/cli/deploy.(*DeployOptions).uploadConfig(0xc0008e4000)
	/home/runner/work/kubeclipper/kubeclipper/pkg/cli/deploy/deploy.go:794 +0x1cf
github.com/kubeclipper/kubeclipper/pkg/cli/deploy.(*DeployOptions).RunDeploy(0xc0008e4000)
	/home/runner/work/kubeclipper/kubeclipper/pkg/cli/deploy/deploy.go:434 +0x205
github.com/kubeclipper/kubeclipper/pkg/cli/deploy.NewCmdDeploy.func1(0xc0008afb80?, {0xc00031cb40?, 0x4?, 0x4?})
	/home/runner/work/kubeclipper/kubeclipper/pkg/cli/deploy/deploy.go:160 +0x5d
github.com/spf13/cobra.(*Command).execute(0xc0008afb80, {0xc00031cb00, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc0008af180)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/home/runner/work/kubeclipper/kubeclipper/cmd/kcctl/main.go:30 +0x4a
[root@localhost ~]#

**Comment by xy2019devl** [comment]
[root@localhost ~]# netstat -an |grep :8080
tcp        0      0 192.168.3.79:53098      192.168.3.79:8080       ESTABLISHED
tcp6       0      0 :::8080                 :::*                    LISTEN     
tcp6       0      0 ::1:8080                ::1:40650               ESTABLISHED
tcp6       0      0 ::1:40650               ::1:8080                ESTABLISHED
tcp6       0      0 192.168.3.79:8080       192.168.3.79:53098      ESTABLISHED
[root@localhost ~]#

**Comment by x893675** [comment]
使用浏览器访问 192.168.3.79 或者使用 kcctl login 看看是否正常

**Comment by xy2019devl** [comment]
[root@localhost k8s]# kcctl login --host http://127.0.0.1 --username admin --password Thinkbig1
WARNING! Using --password via the CLI is insecure.
[root@localhost k8s]# kcctl login --host http://127.0.0.1 --username admin
Please input password for user admin: 
[root@localhost k8s]# ls
v1.23.6
[root@localhost k8s]# pwd
/opt/kubeclipper-server/resource/k8s
[root@localhost k8s]# NODE=$(kcctl get node -o yaml|grep ipv4DefaultIP:|sed 's/ipv4DefaultIP: //')
[root@localhost k8s]# kcctl create cluster --master $NODE --name demo --untaint-master
[2022-10-24T13:48:33+08:00][INFO] use default containerd version 1.6.4
[2022-10-24T13:48:33+08:00][INFO] use default k8s version v1.23.6
+------+-------------------------------+
| NAME |       CREATE TIMESTAMP        |
+------+-------------------------------+
| demo | 2022-10-24 13:48:33 +0800 CST |
+------+-------------------------------+
[root@localhost k8s]# kcctl get cluster -o yaml|grep status -A5
status:
  phase: Installing
  versions:
    apiserver: ""
    controlPlane: ""
    controllerManager: ""
[root@localhost k8s]#

**Comment by xy2019devl** [comment]
这个/kind need-verify 在哪个目录下执行？

**Comment by lixd** [comment]
cased by  [this code](https://github.com/kubeclipper/kubeclipper/blob/b5fb50a5302aa09aa17860fca50a1519ca2190f4/pkg/cli/deploy/deploy.go#L430-L434)
when etcd or kc-server start slow,maybe case this issue。

we need add a way to check is etcd or kc-server started.

@xy2019devl  are you interested to fixed it?

**Comment by lixd** [comment]
/clsoe
fixed by #492
