### ISSUE TITLE
kc-server should support FIP

### ISSUE THREAD

**Issue by wu-wenxiang** [kubeclipper/kubeclipper#483]
**What's it about?**

kc-server should support FIP.

**What's the reason why we need it?**

I believe this is an important feature for KubeClipper. There're a few use cases:

* kc-agent -> FIP -> kc-server

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

```bash
kcctl deploy --server 106.15.46.14 --ip-detect=interface=eth0 --agent 172.18.76.10 --pkg https://oss.kubeclipper.io/release/release-1.3/kc-amd64.tar.gz --pk-file ~/.ssh/id_rsa
```

```console
root@kc-agent:~# kcctl deploy --server 106.15.46.14 --ip-detect=interface=eth0 --agent 172.18.76.10 --pkg https://oss.kubeclipper.io/release/release-1.3/kc-amd64.tar.gz --pk-file ~/.ssh/id_rsa
[2022-12-09T17:05:27+08:00][INFO] ============>kc-etcd PRECHECK ...
[2022-12-09T17:05:27+08:00][INFO] ============>kc-etcd PRECHECK OK!
[2022-12-09T17:05:27+08:00][INFO] ============>kc-server PRECHECK ...
[2022-12-09T17:05:28+08:00][INFO] ============>kc-server PRECHECK OK!
[2022-12-09T17:05:28+08:00][INFO] ============>kc-agent PRECHECK ...
[2022-12-09T17:05:28+08:00][INFO] ============>kc-agent PRECHECK OK!
[2022-12-09T17:05:28+08:00][INFO] ============>TIME-LAG PRECHECK ...
[2022-12-09T17:05:28+08:00][INFO] BaseLine Time: 2022-12-09T17:05:28+08:00
[2022-12-09T17:05:28+08:00][INFO] [172.18.76.10] -0.378135532 seconds
[2022-12-09T17:05:28+08:00][INFO] [106.15.46.14] -0.378135532 seconds
[2022-12-09T17:05:28+08:00][INFO] all nodes time lag less then 5 seconds
[2022-12-09T17:05:28+08:00][INFO] ============>TIME-LAG PRECHECK OK!
[2022-12-09T17:05:28+08:00][INFO] ============>NTP PRECHECK ...
[2022-12-09T17:05:28+08:00][INFO] ============>NTP PRECHECK OK!
[2022-12-09T17:05:28+08:00][INFO] ============>sudo PRECHECK ...
[2022-12-09T17:05:28+08:00][INFO] ============>sudo PRECHECK OK!
[2022-12-09T17:05:28+08:00][INFO] ============>ipDetect PRECHECK ...
[2022-12-09T17:05:28+08:00][INFO] ============>ipDetect PRECHECK OK!
[2022-12-09T17:05:30+08:00][INFO] [106.15.46.14]transfer total size is: 1.64KB ;speed is 1KB
[2022-12-09T17:05:31+08:00][INFO] [106.15.46.14]transfer total size is: 1.09KB ;speed is 1KB
[2022-12-09T17:05:32+08:00][INFO] [106.15.46.14]transfer total size is: 1.64KB ;speed is 1KB
[2022-12-09T17:05:33+08:00][INFO] [106.15.46.14]transfer total size is: 1.23KB ;speed is 1KB
[2022-12-09T17:05:34+08:00][INFO] [106.15.46.14]transfer total size is: 1.64KB ;speed is 1KB
[2022-12-09T17:05:35+08:00][INFO] [106.15.46.14]transfer total size is: 1.24KB ;speed is 1KB
[2022-12-09T17:05:36+08:00][INFO] [106.15.46.14]transfer total size is: 1.64KB ;speed is 1KB
[2022-12-09T17:05:37+08:00][INFO] [106.15.46.14]transfer total size is: 1.24KB ;speed is 1KB
[2022-12-09T17:05:39+08:00][INFO] [106.15.46.14]transfer total size is: 1.64KB ;speed is 1KB
[2022-12-09T17:05:40+08:00][INFO] [106.15.46.14]transfer total size is: 1.25KB ;speed is 1KB
[2022-12-09T17:05:41+08:00][INFO] [106.15.46.14]transfer total size is: 1.64KB ;speed is 1KB
[2022-12-09T17:05:42+08:00][INFO] [106.15.46.14]transfer total size is: 1.27KB ;speed is 1KB
[2022-12-09T17:05:43+08:00][INFO] [106.15.46.14]transfer total size is: 1.64KB ;speed is 1KB
[2022-12-09T17:05:44+08:00][INFO] [106.15.46.14]transfer total size is: 1.27KB ;speed is 1KB
[2022-12-09T17:05:45+08:00][INFO] [172.18.76.10]transfer total size is: 1.64KB ;speed is 1KB
[2022-12-09T17:05:45+08:00][INFO] [172.18.76.10]transfer total size is: 1.09KB ;speed is 1KB
[2022-12-09T17:05:46+08:00][INFO] [172.18.76.10]transfer total size is: 1.64KB ;speed is 1KB
[2022-12-09T17:05:47+08:00][INFO] [172.18.76.10]transfer total size is: 1.27KB ;speed is 1KB
[2022-12-09T17:05:47+08:00][INFO] [172.18.76.10]transfer total size is: 1.64KB ;speed is 1KB
[2022-12-09T17:05:48+08:00][INFO] [172.18.76.10]transfer total size is: 1.27KB ;speed is 1KB
[2022-12-09T17:05:48+08:00][INFO] ------ Send packages ------
--2022-12-09 17:05:48--  https://oss.kubeclipper.io/release/release-1.3/kc-amd64.tar.gz
Resolving oss.kubeclipper.io (oss.kubeclipper.io)... 161.117.155.63
Connecting to oss.kubeclipper.io (oss.kubeclipper.io)|161.117.155.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1040822149 (993M) [application/x-gzip]
Saving to: ‘kc-amd64.tar.gz’

kc-amd64.tar.gz                 100%[=======================================================>] 992.60M  11.4MB/s    in 85s     

2022-12-09 17:07:14 (11.6 MB/s) - ‘kc-amd64.tar.gz’ saved [1040822149/1040822149]

106.15.46.14: done!   
172.18.76.10: done!   
[2022-12-09T17:09:59+08:00][INFO] ------ Install kc-etcd ------
[2022-12-09T17:10:05+08:00][INFO] ------ Install kc-server ------
[2022-12-09T17:10:26+08:00][INFO] ------ Install kc-agent ------
[2022-12-09T17:10:27+08:00][INFO] ------ Install kc-console ------
[2022-12-09T17:10:28+08:00][INFO] ------ Delete intermediate files ------
[2022-12-09T17:10:28+08:00][INFO] ------ Dump configs ------
[2022-12-09T17:10:28+08:00][INFO] ------ Upload configs ------
[2022-12-09T17:10:28+08:00][FATAL] error during connect: Post "http://106.15.46.14:8080/oauth/login": dial tcp 106.15.46.14:8080: connect: connection refused
goroutine 1 [running]:
github.com/kubeclipper/kubeclipper/pkg/cli/logger.stacks(0x0)
	/home/runner/work/kubeclipper/kubeclipper/pkg/cli/logger/logger.go:163 +0x89
github.com/kubeclipper/kubeclipper/pkg/cli/logger.(*loggingT).output(0x228da20?, 0xc000718180?, 0x3)
	/home/runner/work/kubeclipper/kubeclipper/pkg/cli/logger/logger.go:130 +0x75
github.com/kubeclipper/kubeclipper/pkg/cli/logger.(*loggingT).println(0xc000a8b888?, 0x22abd20?, {0xc000a8b8a0, 0x1, 0x1})
	/home/runner/work/kubeclipper/kubeclipper/pkg/cli/logger/logger.go:150 +0x85
github.com/kubeclipper/kubeclipper/pkg/cli/logger.Fatal(...)
	/home/runner/work/kubeclipper/kubeclipper/pkg/cli/logger/logger.go:320
github.com/kubeclipper/kubeclipper/pkg/cli/deploy.(*DeployOptions).uploadConfig(0xc0007e0360)
	/home/runner/work/kubeclipper/kubeclipper/pkg/cli/deploy/deploy.go:792 +0x1d8
github.com/kubeclipper/kubeclipper/pkg/cli/deploy.(*DeployOptions).RunDeploy(0xc0007e0360)
	/home/runner/work/kubeclipper/kubeclipper/pkg/cli/deploy/deploy.go:439 +0x235
github.com/kubeclipper/kubeclipper/pkg/cli/deploy.NewCmdDeploy.func1(0xc000504f00?, {0xc0007e07e0?, 0x9?, 0x9?})
	/home/runner/work/kubeclipper/kubeclipper/pkg/cli/deploy/deploy.go:152 +0x5d
github.com/spf13/cobra.(*Command).execute(0xc000504f00, {0xc0007e0750, 0x9, 0x9})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc000504500)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/home/runner/work/kubeclipper/kubeclipper/cmd/kcctl/main.go:30 +0x4a
```

/kind feature-request

**Comment by simonyangcj** [comment]
是不是加了什么逻辑，眼本 server -> client ，只要求 client 能访问 server ，server 没必要通 client 的，server 只在组 端口验活时，否个 fip 就行了

**Comment by x893675** [comment]
> 是不是加了什么逻辑，原本 server -> client ，只要求 client 能访问 server ，server 没必要通 client 的，server 只在主动检查 client 端口验活时需要个 fip 就行了，原本 installer 里可以每个 client 设置 fip 的

@simonyangcj 节点终端和集群kubectl终端需要server能够访问节点
